select * from customer
limit 10;

# 1. what is the total revenue generated by male vs female customers?
select Gender, sum(purchase_amount) as revenue # alias is used to create temporary column name 
from customer
group by Gender; 

# 2. Which customers used a discount but still spent more than the average purchase amount ?
select customer_id, purchase_amount  
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

# 3. which are the top 5 products with the highest average review rating 

select item_purchased, AVG(review_rating) as "AVERAGE PRODUCT RATING"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

# 4. Compare the average purchase amounts between standard and express shipping 

select shipping_type,
ROUND(AVG(purchase_amount), 2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

# 5.Do subscribed customers spend more? Compare average spend and total revenue between subsdcribers and non subscribers

select subscription_status,
count(customer_id) as total_customers,
round(AVG(purchase_amount), 2) as avgSpend,
round(SUM(purchase_amount), 2) as totalRevenue 
from customer
group by subscription_status
order by avgSpend desc;

# 6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    ROUND(
        SUM(CASE 
                WHEN discount_applied = 'Yes' THEN 1 
                ELSE 0 
            END) / COUNT(*) * 100,
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

# 7. Segment customers into new, returning and loyal based on their total number of previous purchases, and show the count of each segment
with customer_type as (
	select customer_id, previous_purchases,
    CASE
		when previous_purchases = 1 then 'New'
        when previous_purchases between  2 and 10 then 'Returning'
        else 'loyal'
        end as customer_segment 
	from customer
	)
    
    select customer_segment, count(*) as 'Number of customers'
    from customer_type
    group by customer_segment;

# 8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

# 9. Are customers who are repeat buyers (more than 5 previous purchases)also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5 
group by subscription_status;

# 10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;